#! /bin/bash

BIN=/usr/bin/chromium

# Run normally on privved containers or modified un non priv
if grep -q 'Seccomp:	0' /proc/1/status; then
  ${BIN} --password-store=basic --disable-dev-shm-usage "$@"
else
  ${BIN} --password-store=basic --no-sandbox --test-type --disable-dev-shm-usage "$@"
fi
