#!/bin/bash

set -eo pipefail
set -x

cleanup() {
  [ -n "$workspaces_container_id" ] && docker container stop "$workspaces_container_id"
}

build_workspaces_image() {
  docker build -t "$workspaces_image" -f Workspaces.dockerfile .
}

trap cleanup EXIT

set -x
workspaces_image=kasmweb/ubuntu-jammy-desktop:develop
workspaces_container_id=$(docker run --detach --rm -it --shm-size=512m -p 6901:6901 -e VNC_PW=password "$workspaces_image")
workspaces_container_ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $workspaces_container_id)
export workspaces_container_ip
sleep 5

KASMVNC_IMAGE_TO_TEST_ON="$workspaces_image"
export KASMVNC_IMAGE_TO_TEST_ON
./test-and-render-report.sh
