#!/usr/bin/python3

from selenium import webdriver

# Define login credentials
username = "kasm_user"
password = "password"
url = "https://10.1.1.5:6901"

## Webdriver setup ##
chrome_options = webdriver.ChromeOptions()
chrome_options.binary_location = '/usr/bin/chromium-wrapped'
chrome_options.add_argument("--headless")
chrome_options.add_argument("--user-data-dir=/home/docker/user-data")
chrome_options.add_argument("--allow-running-insecure-content")
chrome_options.add_argument("--disable-web-security")

# docker flags
chrome_options.add_argument("--disable-gpu")
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--disable-extensions")
chrome_options.add_argument("--disable-dev-shm-usage")
# no ssl errors
chrome_options.add_argument('--ignore-certificate-errors')
# allow automatic file download and clear all perms
chrome_options.add_experimental_option("prefs", {
  "download.default_directory": "/config/Downloads",
  "download.prompt_for_download": False,
  "download.directory_upgrade": True,
  "safebrowsing_for_trusted_sources_enabled": False,
  "safebrowsing.enabled": False,
  "profile.default_content_setting_values.media_stream_mic": 1,
  "profile.default_content_setting_values.media_stream_camera": 1,
  "profile.default_content_setting_values.geolocation": 1,
  "profile.default_content_setting_values.notifications": 1
})
# enable fake microphone
chrome_options.add_argument('--use-fake-device-for-media-stream')
chrome_options.add_argument('--use-fake-ui-for-media-stream')
# enable fake webcam
chrome_options.add_argument("--use-fake-ui-for-media-stream")
chrome_options.add_argument("--use-fake-device-for-media-stream")
# options and timeouts
driver = webdriver.Chrome(options=chrome_options)
driver.set_page_load_timeout(60)
driver.implicitly_wait(15)
# Initial login
KASM_HOST = '10.1.1.5'
KASM_PORT = '6901'
driver.get(f"https://{username}:{password}@{KASM_HOST}:{KASM_PORT}")
driver.set_window_size(1920, 1080)

import time
time.sleep(5)
driver.get_screenshot_as_file('screenshot.png')
