#!/bin/bash

set -e

fetch_ami_id () {
  local image_name="$1"
  local owner_id="$2"
  local arch="$3"

  aws ec2 describe-images --filters \
    "Name=name,Values=$image_name*" \
    "Name=owner-id,Values=$owner_id" \
    "Name=state,Values=available" \
    "Name=architecture,Values=$arch" \
    "Name=virtualization-type,Values=hvm" \
    "Name=root-device-type,Values=ebs" \
    "Name=image-type,Values=machine" \
    --query 'sort_by(Images, &CreationDate)[-1].[ImageId]' \
    --output 'text' \
    --region us-east-1
}

AMI=$(fetch_ami_id "ubuntu/images/hvm-ssd/ubuntu-jammy-22.04" 099720109477 x86_64)
echo "$AMI"
